services:
 chroma:
   image: chromadb/chroma:latest
   ports:
     - "8000:8000"
   volumes:
     - chroma_data:/chroma/chroma
   environment:
     - ALLOW_RESET=true 
     - CHROMA_SERVER_AUTH_TOKEN=${CHROMA_AUTH_TOKEN}
     - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token.TokenAuthClientProvider
     - CHROMA_SERVER_AUTH_PROVIDER=token

 postgres:
   image: postgres:15-alpine
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   environment:
     - POSTGRES_USER=${POSTGRES_USER:-athena}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-athenapassword}
     - POSTGRES_DB=${POSTGRES_DB:-athenadb}
   healthcheck:
     test: ["CMD-SHELL", "pg_isready -U athena"]
     interval: 10s
     timeout: 5s
     retries: 5

 redis:
   image: redis:7-alpine
   ports:
     - "6379:6379" 
   volumes:
     - redis_data:/data
   command: redis-server --requirepass ${REDIS_PASSWORD:-athenapass}
   healthcheck:
     test: ["CMD", "redis-cli", "ping"]
     interval: 10s
     timeout: 5s
     retries: 5

 pgadmin:
   image: dpage/pgadmin4
   ports:
     - "5050:80"
   environment:
     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@athena.ai}
     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
   depends_on:
     - postgres

volumes:
 chroma_data:
 postgres_data:
 redis_data: